app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_info:
    path: /user/{id}/{width}/{height}/{bgcolor}/{fontcolor}
    defaults:
        _controller: AppBundle:User:info
    requirements:
        id: '[\d]+'
        width: '[\d]+'
        height: '[\d]+'
        bgcolor: '[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3}'
        fontcolor: '[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3}'

